import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/message_model.dart';

class ChatService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // Collection References
  CollectionReference get _messagesCollection =>
      _firestore.collection('group_chat_messages');

  CollectionReference get _typingCollection =>
      _firestore.collection('typing_status');

  // Stream of messages
  Stream<List<Message>> getMessages() {
    return _messagesCollection
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) {
        return Message.fromMap(doc.data() as Map<String, dynamic>, doc.id);
      }).toList();
    });
  }

  // Send a message
  Future<void> sendMessage(String text, bool isAuthority, String senderName,
      String? senderProfileUrl) async {
    final user = _auth.currentUser;
    if (user == null) return;

    final message = Message(
      id: '', // Will be generated by firestore
      senderId: user.uid,
      senderName: senderName,
      text: text,
      timestamp: DateTime.now(),
      isAuthority: isAuthority,
      senderProfileUrl: senderProfileUrl,
    );

    await _messagesCollection.add(message.toMap());
  }

  // Delete message
  Future<void> deleteMessage(String messageId) async {
    await _messagesCollection.doc(messageId).delete();
  }

  // Edit message
  Future<void> editMessage(String messageId, String newText) async {
    await _messagesCollection.doc(messageId).update({
      'text': newText,
      'isEdited': true,
    });
  }

  // Toggle Reaction
  Future<void> toggleReaction(String messageId, String emoji) async {
    final user = _auth.currentUser;
    if (user == null) return;

    final docRef = _messagesCollection.doc(messageId);

    // We need to use a transaction or read-then-write to check existing reaction
    // For simplicity with map, we can read then update.
    final docSnapshot = await docRef.get();
    if (!docSnapshot.exists) return;

    final data = docSnapshot.data() as Map<String, dynamic>;
    final reactions = Map<String, String>.from(data['reactions'] ?? {});

    if (reactions[user.uid] == emoji) {
      // Remove reaction if same
      reactions.remove(user.uid);
    } else {
      // Add/Update reaction
      reactions[user.uid] = emoji;
    }

    await docRef.update({'reactions': reactions});
  }

  // Update typing status
  Future<void> updateTypingStatus(bool isTyping) async {
    final user = _auth.currentUser;
    if (user == null) return;

    if (isTyping) {
      await _typingCollection.doc(user.uid).set({
        'senderName': user.displayName ??
            'Unknown', // Ideally fetch from user profile but auth display name is faster fallback
        'timestamp': FieldValue.serverTimestamp(),
      });
    } else {
      await _typingCollection.doc(user.uid).delete();
    }
  }

  // Get currently typing users
  Stream<List<String>> getTypingUsers() {
    return _typingCollection.snapshots().map((snapshot) {
      return snapshot.docs
          .where((doc) => doc.id != _auth.currentUser?.uid) // Exclude self
          .map((doc) => doc['senderName'] as String)
          .toList();
    });
  }
}
