// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY1UKhIbFc1JYXJCusFcZKWxehywbJ-8U',
    appId: '1:556446695283:web:e767096bffd7dc68298f06',
    messagingSenderId: '556446695283',
    projectId: 'smart-tourist-project',
    authDomain: 'smart-tourist-project.firebaseapp.com',
    storageBucket: 'smart-tourist-project.firebasestorage.app',
    measurementId: 'G-2BB2CHW1RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPZ-TzOjqAuYVk2ftF_PtQ5nU_baT2Cac',
    appId: '1:556446695283:android:cec094790c0c3d2a298f06',
    messagingSenderId: '556446695283',
    projectId: 'smart-tourist-project',
    storageBucket: 'smart-tourist-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb3ls6g-rfmdqL9VjcOUSpHTU1RMaxgwo',
    appId: '1:556446695283:ios:cc28969d2a762cea298f06',
    messagingSenderId: '556446695283',
    projectId: 'smart-tourist-project',
    storageBucket: 'smart-tourist-project.firebasestorage.app',
    iosBundleId: 'tech.safetravel.smarttourist.smartTouristApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb3ls6g-rfmdqL9VjcOUSpHTU1RMaxgwo',
    appId: '1:556446695283:ios:cc28969d2a762cea298f06',
    messagingSenderId: '556446695283',
    projectId: 'smart-tourist-project',
    storageBucket: 'smart-tourist-project.firebasestorage.app',
    iosBundleId: 'tech.safetravel.smarttourist.smartTouristApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY1UKhIbFc1JYXJCusFcZKWxehywbJ-8U',
    appId: '1:556446695283:web:dd2f85541f718157298f06',
    messagingSenderId: '556446695283',
    projectId: 'smart-tourist-project',
    authDomain: 'smart-tourist-project.firebaseapp.com',
    storageBucket: 'smart-tourist-project.firebasestorage.app',
    measurementId: 'G-VJ05DFJBRE',
  );

}